apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    app.kubernetes.io/part-of: campusconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        app.kubernetes.io/part-of: campusconnect
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
          envFrom:
            - configMapRef:
                name: campusconnect-config
          readinessProbe:
            httpGet: { path: /health, port: 8000 }
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: 8000 }
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits: { memory: 256Mi }
