apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
    app.kubernetes.io/part-of: campusconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        app.kubernetes.io/part-of: campusconnect
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: order-service
          image: order-service:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: "3003"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: ORDER_MONGO_URI
          envFrom:
            - configMapRef:
                name: campusconnect-config
          readinessProbe:
            httpGet: { path: /, port: 3003 }
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: 3003 }
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits: { memory: 256Mi }
